package com.management.eventdrivenordermanagementsystem.messaging.event;

public enum EventType {
    ORDER_CREATED,
    INVENTORY_RESERVATION_REQUESTED,
    INVENTORY_RESERVED,
    INVENTORY_RESERVATION_REJECTED,
    PAYMENT_AUTHORIZATION_REQUESTED,
    PAYMENT_AUTHORIZED,
    PAYMENT_FAILED,
    ORDER_CONFIRMED,
    ORDER_CANCELLED,
    INVENTORY_RELEASE_REQUESTED,
    INVENTORY_RELEASED,
    PAYMENT_COMPENSATION_REQUESTED,
    PAYMENT_VOIDED,
    PAYMENT_REFUNDED,
    SHIPMENT_PREPARATION_REQUESTED,
    SHIPMENT_PREPARATION_STARTED
}

